
name: ETL Pipeline development  Demo

#trigger event
# when github action call these evemt 
on:
  push:
    branches:
      - main


jobs:
  extract-data:
    runs-on: ubuntu-latest
     
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup python
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
         python-version: '3.10' 
      



      - name: show python version
        run: python --version

      - name: Run extract.py
        run: python extract.py

  transform-data:
    runs-on: ubuntu-latest
    needs: extract-data

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run transform.py
        run: python transform.py

  load-data-job:
    runs-on: ubuntu-latest
    needs: transform-data

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Run load.py
        run: python load.py






